spring.application.name=backend
server.port=8080

spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/krevia
spring.datasource.username=krevia_user
spring.datasource.password=krevia_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration